### ISSUE TITLE
Unsupported manufacturer (Qualcomm)

### ISSUE THREAD

**Issue by gciandro13** [securing/gattacker#15]
I need to clone Bluetooth MAC adress of an Arduino (target device), in my Ubuntu laptop (peripheral BLENO device), starting the script "./mac_adv" that calls bdaddr function, but I receive "Unsupported manufacturer".
I've got a Qualcomm manufacturer, so probably that could be the problem because only some specific manufacturers are supported.
Is there any advice in order to solve this issue ?

**Comment by jslawek** [comment]
Hi,

the bdaddr tool, which we use to change MAC address of Bluetooth adapter, is not part of GATTacker. It is part of BlueZ, and just added as helper for convenience.
As you noticed, it supports only a selection of chipsets (including Cambridge Silicon Radio, Broadcom, Marvell, ...). The current source code can be found here in BlueZ git repository:
https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/tools/bdaddr.c
In order to add support for other chipsets, you would need to figure the manufacturer's HCI commands to do it. You should ask this question to BlueZ developers, as this is unfortunatelly out of our scope.

What is the exact model of your adapter's chipset? CSR has been acquired by Qualcomm recently, so there is a slight chance it is supported, but just not recognized.
If not, the easiest way to resolve your issue would be to use a different adapter. CSR8510 is the most common USB BLE adapter, pretty available everywhere for about 5$, and proved to be reliable for changing MAC address.

**Comment by gciandro13** [comment]
Thank you very much for the answer.
Specifically, I've got _Qualcomm Atheros Bluetooth 4.1_ model: I don't know if it's going under the possibility that it is supported but not recognized from bdaddr tools.
I think that I will try to buy a CSR8510 adapter to get the possibility to change the MAC address, in order to solve that issue.
One question: once I installed it, do I have to change something from the Device Manager or automatically Gattacker and bdaddr tools will be able to see two different bluetooth adapter on my laptop?

**Comment by jslawek** [comment]
I'm afraid Atheros is not supported by bdaddr, so your only option is to try with other adapter.

Regarding two different bluetooth adapters - just bring down the other one (hciconfig hciX down), and GATTacker should use the first one available by default. But to be sure, you can also setup manually in config.env NOBLE_HCI_DEVICE_ID or BLENO_HCI_DEVICE_ID - depending if you plan to use it as spoofed device emulator, or as master ("client") connecting to original peripheral device.

**Comment by gciandro13** [comment]
Ok: then, i will try with the CSR bluetooth adapter.
