### ISSUE TITLE
TypeError on scanning if the EIR is empty

### ISSUE THREAD

**Issue by forte916** [securing/gattacker#8]
Hi

Here is a issue report.

* Description:
    * When I scan broadcasted advertisements, node crashes in utils.js if the EIR is empty.
    * I think that device can support both classic and BLE, but I'm not sure (because I'm not the owner).
    * According to the specification, the EIR could be empty. (See the footnote)

* Solution:
    * I checked utils.js and fix it with the following patch, and it works.

* Version:
    * current version (git clone)

* OS:
    * Ubuntu 16.04 LTS (on Virtual Box)

* Here is the console logs:
```
$ sudo node ws-slave.js
GATTacker ws-slave
ws -> connection
ws -> send: {"type":"stateChange","state":"poweredOn"}
ws -> message: {"action":"startScanning"}
ws -> send: {"type":"startScanning"}
ws -> send: {"type":"discover","peripheralId":"00e04cd5ddf8","address":"00:e0:4c:d5:dd:f8","addressType":"public","connectable":true,"advertisement":{"serviceUuids":[],"manufacturerData":null,"serviceData":"","eir":"","scanResponse":null},"rssi":-78}
ws -> close
ws -> send: {"type":"stopScanning"}
```

```
$ node scan.js
Ws-slave address: 127.0.0.1
on open
poweredOn
Start scanning.
/home/iotsec/node_modules/gattacker/lib/utils.js:105
                      eir: advertisement.eir.toString('hex'),
                                            ^

TypeError: Cannot read property 'toString' of null
    at /home/iotsec/node_modules/gattacker/lib/utils.js:105:45
    at /home/iotsec/node_modules/gattacker/lib/utils.js:87:7
    at f (/home/iotsec/node_modules/once/once.js:25:25)
    at Glob.<anonymous> (/home/iotsec/node_modules/glob/glob.js:151:7)
    at emitOne (events.js:96:13)
    at Glob.emit (events.js:188:7)
    at Glob._finish (/home/iotsec/node_modules/glob/glob.js:199:8)
    at done (/home/iotsec/node_modules/glob/glob.js:184:14)
    at Glob._processReaddir2 (/home/iotsec/node_modules/glob/glob.js:410:12)
    at /home/iotsec/node_modules/glob/glob.js:373:17
```

* Here is the patch:
```diff
diff --git a/lib/utils.js b/lib/utils.js
index f8d67ad..49b84be 100644
--- a/lib/utils.js
+++ b/lib/utils.js
@@ -102,7 +102,7 @@ function saveAdvertisement(peripheralId, address, addressType, connectable, adve
         //keep buffers as hex strings (by default buffers stringify unreadable into json)
         advToJson = {
                       id: peripheralId,
-                      eir: advertisement.eir.toString('hex'),
+                      eir: advertisement.eir ? advertisement.eir.toString('hex') : '',
                       scanResponse: advertisement.scanResponse ? advertisement.scanResponse.toString('hex') : null,
                       decodedNonEditable : {
                         localName: advertisement.localName ? advertisement.localName : '',
```

* Reference
    * BLUETOOTH SPECIFICATION Version 4.2 [Vol 2, Part B] page 172
        * 8.4.3 Inquiry Response Substate

> If the slave's extended inquiry response data is all zeroes the slave shall only return an FHS packet with the EIR bit set to zero.

**Comment by securing** [comment]
Thanks!
I have merged your PR.

The spec you cited (Vol 2) is for BR/EDR (previous Bluetooth versions). Low Energy is in Vol 6. The "EIR" in utils.js is just advertising data (most devices use "connectable undirected advertising"). Specification defines it in Vol 6 chapter "2.3 Advertising Channel PDU".

I have seen a few devices that do not respond to Scan Request - that's why this exception was covered in utils.js. But so far I have not met any device that did advertise "empty" data in the ADV_IND PDU. Specification does not strictly enforce nor deny it, but such behaviour probably would not make sense - scanning apps usually filter by advertised data, not MAC address. 

I would rather suspect your case may be a result of some kind of missing data (e.g. performance timings of your VM <-> BLE adapter), or other bug. You may also check the actual advertisements of the peripheral device using e.g. a BLE scanner mobile app or command-line Bluez utils.

**Comment by forte916** [comment]
Thank you for the merge and advise.

I don't know where the device is, just got its advertisement in the air.
And the device is gone now. It could be the prototype or debug use.

By the way, I checked with nRF Connect(BLE scanner app), it says EIR is empty.
